[package]
name = "ai-hil-debugger"
version = "1.0.0"
description = "AI-Driven Embedded Hardware-in-the-Loop (HIL) Debugger"
authors = ["zenghuiJIA <zenghui.JIA@ingchips.com>"]
license = "Apache-2.0"
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
serialport = "4.7"
tokio = { version = "1", features = ["full"] }
sysinfo = "0.33"
windows-sys = { version = "0.59", features = [
    "Win32_System_JobObjects",
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Registry",
    "Win32_UI_WindowsAndMessaging"
] }

